### PR TITLE
Feat: added support for PERF_EVENT_IOC_* constants

### PR DESCRIPTION
**Pull request by Sl1mb0**
* Moved `event.rs` into `event/mod.rs`.
* Added `event/constants.rs`
  * contains necessary macros for generating all `PERF_EVENT_IOC_*` constants
  * constants are located in `event/constants.rs`
* cargo test passes!

### CODE REVIEW

**Review by kagutaba256 — APPROVED** [review]
Ran tests on my machine and a fresh ubuntu vm, `syscall_test` and everything else passed on both. These macros work great!

**Review by Boursler — COMMENTED** [review]
Really exciting that you've got this working! I had two suggestions:
- I know in C we have to use macros for this case, but in Rust it might be cool to implement with const functions: https://doc.rust-lang.org/reference/const_eval.html#const-functions. Reading about them it seems to me they meet our need here and would avoid the reliance on macros.
- Should the perf_event_open part of mod.rs be in a file with a name like perf_event_open.rs or something like that? I definitely see the argument for the syscall_test to remain in mod.rs but it seemed to me it might be better to have that definition elsewhere. Wdyt?

**Comment by Sl1mb0** [comment]
It's funny that you mention that, because I was just reading [this article](https://opensource.com/article/20/1/c-vs-rust-abstractions). I agree that we should implement them as const functions. I also think we should define size constants as well instead of using std::mem::size_of.

To your second point, yes. I think it just makes it cleaner. If we have to add other stuff then it makes it easy to find. 

On a somewhat related note, I think our tool would eventually want to abstract all the system specific stuff down to specific events. Obviously this isn't well thought out, but I like the idea of using something like:

`use Event::{ContextSwitch, L1CacheMiss,..`

You could then do something like `ContextSwitch.reset_counter(), ContextSwitch.stop_counter(), start_counter()` etc. I don't know how well this works for other events, but that's what I thought.

Those data structures would handle all the necessary system calls. The system calls and their necessary files themselves could then all be in a single module `perf_event_open`, that we can then each use when building the data structures for the events we chose.

This is definitely something we should hash out before this PR gets submitted.

**Review by ScherrerMichael — CHANGES_REQUESTED** [review]
```
failures:

---- event::syscall_test stdout ----
thread 'event::syscall_test' panicked at 'assertion failed: `(left != right)`
  left: `-1`,
 right: `-1`: Testing for failure', src/event/mod.rs:61:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    event::syscall_test

test result: FAILED. 32 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

`cargo test` failed for me on: `assert_ne!(fd, -1, "Testing for failure");`



Ran on Linux Mint 
Kernel: 5.4.0-77
Intel© Core™ i7-8565U CPU @ 1.80GHz × 4

**Comment by Sl1mb0** [comment]
Did you turn off `/proc/sys/kernel/perf_event_paranoid`?

**Comment by ScherrerMichael** [comment]
ooh that might be it, I'll do that right now.

**Comment by ScherrerMichael** [comment]
`perf`ect, works for me!

I used: `sudo sysctl kernel.perf_event_paranoid=1`

Should we document that instruction?

**Review by ScherrerMichael — APPROVED** [review]

**Review by Boursler — APPROVED** [review]

**Pull request merged**
