### PR TITLE
Feat: added interface for interacting with `perf_event` related file descriptors.

### PR DESCRIPTION
**Pull request by Sl1mb0**
See issue #45 for information on functions that don't work. Otherwise:
- [x] `cargo test` passes
- [x] `cargo fmt` & `cargo clippy` passes. with a few warnings courtesy of `bindgen`.

I think now is a good time to address the structure of this interface, because for me personally I think there are better names and ways to structure it. One thing I don't like is the use of `include!()` in multiple files. It works, but I think there is a better solution. I also think that the namespaces could be named better e.g. `perf::event::FileDesc::new()` is obviously not good, but it's what I came up with for the time being. Definitely open to suggestions, feedback, and brainstorming.

Further testing is needed but for now. Once `read()` is up, there is enough of an interface to start getting specific event information, and we can build the 'next layer'.

### CODE REVIEW

**Comment by Boursler** [comment]
What about a structure like:
- `event/event.rs`
- `event/mod.rs`
- `event/constants.rs` || `event/ioctlconstants.rs` (or something)
- `event/filedesc.rs` || `event/fd.rs` (because why not)
- We could also have an `event/utils.rs` that would have return and error types for the module defined.
 
`event/event.rs` would contain a wrapper around `perf_event_attr` to accept and transform arguments to that structure, along with `event` functions such as `event.get_count` which would actually call `read` for now although later will also have logic to call `mmap` instead for when that's needed.

It would be nice if we could set it up so the includes could all be in `mod.rs` along with the tests and module declarations, will need to mess with that to see if if it works. 

Personally, I thought `FileDesc::new()` is fine, since instantiating our FileDesc is what we're doing. 

Wdyt? I don't mind creating the files along with the `read` stuff in this PR, if the idea is generally accepted.

**Comment by Sl1mb0** [comment]
I love your idea for `event/event.rs` containing a way to transform arguments to `perf_event_attr`. As it stands creating `perf_event_attr` structs is tedious, so making it less so is something I strongly agree with. I also like that file containing trait implementations for the events themselves e.g. implement `get_count()` as a trait for events. 

I think that for `constants.rs` we should treat all the finicky/weird binding stuff as it's own module that can then be used in `FileDesc`. Things like the constants, the system call wrappers, `use libc::*`, redefinition of `perf_event_attr` etc. would all be contained in that sub-module. We can call the module `sys` or `wrappers` or something like that. So something like 

`event/sys`
`event/fd.rs`
`event/event.rs`
`event/utils.rs`
`event/mod.rs`

And `sys` is a sub module that handles all of finicky weird systems stuff, which is then included in the `fd` module.

Thoughts?

**Comment by Boursler** [comment]
In that case, should we add another layer of abstraction to the functions in `fd.rs`, ie the actual `unsafe` call to `ioctl` gets moved to a wrapper in the `sys` directory? eg:
in `fd.rs`:
   `` 
pub fn refresh(&self, count: u64) -> Result<(), IoError> {

        let ret: i32;
        // passing an argument of 0
        // with this ioctl is undefined behavior.
        if count == 0 {
            return Err(IoError::InvalidArg);
        }

        let arg: *const u64 = &count;
        ret = ioctl(self.0, REFRESH as u64, arg) };
        if ret == -1 {
            return Err(IoError::SysCallFail);
        } 

in `sys/wrappers.rs`:
``
pub fn ioctl(fd: FileDesc, request: u64, arg: *mut u64(or however to make it work)) -> Result <u64, IoError>{
unsafe{...}
} `` 
or however makes it work, just trying to demonstrate the idea.

**Comment by Sl1mb0** [comment]
Yeah. It's probably a little tedious to rewrite it like that but I think it's better to keep all `unsafe` code at the same level. I'll make some commits to this PR that reflect those changes. once it's in a good spot where we agree, we can merge it and then you can add `read` where you need to?

Edit:

I also think that `event/event.rs` should be named `event/open.rs` instead. Yay or nay?

**Comment by Boursler** [comment]
Yeah, I've come around to agreeing that all the unsafe code should be at the same level. I think doing so also makes it easier to have helpful abstractions around the various system calls. 

I think we could also accept this PR and then you could add the ioctl updates in another one tbh. I also went ahead and created the file structure and got it passing cargo tests and stuck my unsafe call to read in that (cunningly named `read_wrap` because words). 

I do have a nit: You have some unnecessary merge commits.

**Review by Boursler — APPROVED** [review]

**Comment by Sl1mb0** [comment]
I did those changes to make sure my repo was up to date when I submitted the PR, but I'm guessing I didn't need to do that for this PR to merge successfully.

Do I understand that correctly?

**Review by ScherrerMichael — APPROVED** [review]
builds, and tests passed!

Great code!

**Comment by ScherrerMichael** [comment]
> I did those changes to make sure my repo was up to date when I submitted the PR, but I'm guessing I didn't need to do that for this PR to merge successfully.
> 
> Do I understand that correctly?

So far I've been creating a new feature branch checked out at `dev:head` before making changes. Doing that ~ if I'm correct ~ saves the hassle of worrying about merge commits.

**Pull request merged**
