### PR TITLE
Briana rustbind

### PR DESCRIPTION
**Pull request by Boursler**
Experimental code for way to use rust bindings in the project.

### CODE REVIEW

**Comment by Sl1mb0** [comment]
Three things sticking out to me so far when trying to test calling the wrapper for `perf_event_open()`.
* There are a lot of fields to initialize in a `perf_event_attr` struct. I have not counted, but I know that it is more than 13. I know that in Rust, you can initialize fields to a default value using `..` but I don't think that works here.
* Some of the fields that are in the C version of the struct, are actually turned on and off via `struct perf_event_attr` `Self` methods. See `exclude_kernel` in `bindings.rs`
* bindgen has (I think?) done a couple things incorrectly, and made calling `perf_event_open()` more tedious:
  * Initializing some fields with the desired enums require use of `as` operator, which is weird and stupid
  * Lengthened symbol names for no discernible reason. Almost all enums have some `_perf_**_ids` prefix, and changing the type of this prefix (in one instance, specifically `_perf_sw_ids`) from `u32` to `u64` in `bindings.rs` fixed the aforementioned initialization problem.

Right now I am working on making a commit to this PR that implements testing the wrapper Briana wrote. The test will pass as long as the system call does not fail. However, initializing a `perf_event_attr` struct is extremely tedious, and I think making it less so is something we should consider exploring.

**Comment by Sl1mb0** [comment]
To solve the issue of tedious `perf_event_attr` struct initialization, I am going to implement the default trait for the `perf_event_attr` struct. I am going to push some commits to this PR that are not complete by any means, but should demonstrate what I am talking about.

**Comment by Sl1mb0** [comment]
After some digging, it turns out that the `BindgenBitfieldUnit` field in the `perf_event_attr` Rust struct serves as a substitute for some of the fields in the C version of the struct. Setting and getting these fields is done via `perf_event_attr` `Self` methods. 

It also looks like we are going to have to implement the `Default` traits by hand for each of `perf_event_atttr__bindgen_ty_*` unions (These are specific fields in `perf_event_attr`. Once that is in place, we can implement the `Default` trait for the `perf_event_attr` struct (`Default` is already implemented for `BindgenBitfieldUnit`).

**Comment by Sl1mb0** [comment]
I have implemented the `Default` traits for  the `perf_event_attr` structs, and have gotten `cargo test` to successfully compile and run. The test fails however.

Personally, I encountered this error when playing around with `perf_event_open` in C. Obviously there are a lot of security concerns as it relates to `perf_event_open()`; to mitigate this the Linux team uses the `/proc/sys/kernel/perf_event_paranoid` to set the privilege that `perf_event_open` has. Anything other than 1 or 0 will yield an error when calling the function. 

This is obviously not ideal, and another way to workaround this, is to set the capability of the executable to have `SYS_CAP_ADMIN` capabilities. I have  done this, and have actually counted hardware instructions to various `printf()` calls. (Hint: it's a lot). 

I am unsure of how to grant this capability to our `cargo test` executable, so that we can verify that our wrapper works. [Though since you can pass options to the executable binary](https://doc.rust-lang.org/cargo/commands/cargo-test.html), it should be possible.


There is also the ENORMOUS issue of the amount of `unsafe` code that will be involved, though we can certainly worry about that later.

I have pushed all of these changes to my `rust-syscall` branch. Upstream of that branch is Briana's PR branch, so if she wants to she can integrate the changes. Otherwise everyone should take a look and see what they think.

**Comment by Sl1mb0** [comment]
Alright everyone, I believe we have a working system call wrapper in Rust. Please check out my [rust-syscall branch](https://github.com/Sl1mb0/perf-rust/tree/rust-syscall).

Please note that `/proc/sys/kernel/perf_event_paranoid` must contain a value of 0 for `cargo test` to succeed. I did not test it with a value of 1.  

Use `/scripts/permit.sh` to change the value of `/proc/sys/kernel/perf_event_paranoid`.

**Comment by Boursler** [comment]
Closing, resolved in PR 21.

**Pull request closed without merging**
