### PR TITLE
Added bindgen support

### LINKED ISSUE #5: Add support for Bindgen
Add bindgen support and initially add open.c to demonstrate use.

### PR DESCRIPTION
**Pull request by ScherrerMichael**
note: I am not sure how to demonstrate using open.c.

### CODE REVIEW

**Review by Boursler — CHANGES_REQUESTED** [review]
Can you drop the merge commits using git rebase -i HEAD~3?

**Comment by ScherrerMichael** [comment]
oops! Trying to figure this out.

**Comment by Sl1mb0** [comment]
On line 10 @ScherrerMichael , you mention being unsure about `println!("cargo:rustc-link-lib=")`. 
I am pretty sure that macro will be necessary for telling Rust where the actual C library is. The bindings should 
also be generated from  `/event/system-call/open.h` and not `linux/perf_event.h` if we are to use the C wrapper. 
We need to build bindings for `ioctl()`, `prctl()`, `read()`, and `mmap()` as well.

**Review by Boursler — COMMENTED** [review]
I think we should have the support for the syscall wrapper done with this PR, so that the issue of how to deal with it is resolved entirely.

**Comment by Sl1mb0** [comment]
I wrote this in the PM, but I wanted to be more clear about my thoughts here.

I think that the system call to `perf_event_open()` should be performed in C. The Rust bindings we generate then would be the minimum necessary for performing a call to `perf_event_open()`. This will reduce the amount of bindings we have. The C static libraries should essentially have any headers that our Rust code does not absolutely need.

Furthermore, we can generate separate bindings and wrappers as needed for the other system calls we need: `read()`, `ioctl()`, and include these in `open.c` and `open.h`. We can build these as wrappers into a single static library and link it to our Rust code. We can then separately generate the bindings necessary for performing each individual system call.

This approach will accomplish a few things:
* Modularity
* Clearly distinguish the layer between our Rust and C code
* Restrict bindings to those only absolutely necessary (less is more)

The only cons I see are that it MAYBE makes things a bit more tedious? We would have to write C code, and test it. But we would have to do that in Rust anyways. We also would need to build and link the wrappers as a static library, but that can be accomplished in the build script. but ultimately if we are relying on tool like `bindgen` (which is still relatively new, and they even said that in some cases it does not generate the right stuff, though I doubt that will happen to us) I would like to minimize how much we use it.

As far as debugging, I also think that in either case, the same problems will arise. As a result of that I would like it to be done 'manually' instead of 'automatically' so that fixing things is easier. (does that make sense?)

I am not going to fight to the death for this idea, but I do believe it is good. I would also like to hear other well-defended approaches.

**Comment by ScherrerMichael** [comment]
@Sl1mb0, Your point does make sense. from what I've read, clutter will be an issue if we only plan to use a subset of code generated by `bindgen`. If we are focusing on size, and organization, it would probably be best to create our own bindings.

**Pull request closed without merging**
